In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("Blinkit_Sales.csv")

In [3]:
df

,Order_ID,Date,City,Product_Name,Category,Quantity,Unit_Price,Total_Sales,Delivery_Time,Customer_Rating,Payment_Mode,Delivery_Type,Seller_Name
0,1001,28-04-2024,Delhi,Wheat Flour 1kg,dairy,two,50.0,250.0,43,4.0,cash,Standard,FreshFarm
1,1002,09-06-2024,delhi,Sugar 1kg,Grocery,3,60.0,180.0,58,NaN,UPI,Standard,BakeHouse
2,1003,12-01-2024,Pune,Cake 500g,Vegetables,4,70.0,280.0,90,NaN,Card,express,FreshFarm
3,1004,2024-06-18,Bengaluru,Onion 1kg,Vegetables,2,55.0,110.0,43,4.7,upi,express,GroceryHub
4,1005,2024/05/15,Jaipur,Banana 1dozen,Grocery,NaN,100.0,300.0,36,4.0,UPI,express,FarmFresh
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,1996,2024/02/01,delhi,Potato 1kg,dairy,2,80.0,160.0,81,4.0,Card,standard,GreenCart
996,1997,2024-06-14,Bengaluru,Chips 200g,grocery,2,40.0,80.0,53,NaN,UPI,Standard,FarmFresh
997,1998,2024-03-31,Delhi,Curd 500g,Grocery,1,100.0,100.0,81,4.7,Card,Express,BakeHouse
998,1999,2024/03/16,Banglore,Namkeen 500g,Bakery,two,85.0,255.0,39,4.2,upi,Express,FreshFarm
999,2000,2024/06/05,Banglore,Rice 1kg,grocery,3,40.0,120.0,47,4.5,UPI,Express,FreshFarm

In [4]:
df.isnull()

,Order_ID,Date,City,Product_Name,Category,Quantity,Unit_Price,Total_Sales,Delivery_Time,Customer_Rating,Payment_Mode,Delivery_Type,Seller_Name
0,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,True,False,False,False
2,False,False,False,False,False,False,False,False,False,True,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,True,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,False,False,False,False,False,False,False,False,False,False,False,False,False
996,False,False,False,False,False,False,False,False,False,True,False,False,False
997,False,False,False,False,False,False,False,False,False,False,False,False,False
998,False,False,False,False,False,False,False,False,False,False,False,False,False
999,False,False,False,False,False,False,False,False,False,False,False,False,False

In [5]:
df.isnull().sum()

Order_ID             0
Date                 0
City                 0
Product_Name         0
Category             0
Quantity           159
Unit_Price          77
Total_Sales         77
Delivery_Time        0
Customer_Rating    245
Payment_Mode         0
Delivery_Type        0
Seller_Name          0
dtype: int64

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Order_ID         1000 non-null   int64
 1   Date             1000 non-null   object
 2   City             1000 non-null   object
 3   Product_Name     1000 non-null   object
 4   Category         1000 non-null   object
 5   Quantity         841 non-null    object
 6   Unit_Price       923 non-null    float64
 7   Total_Sales      923 non-null    float64
 8   Delivery_Time    1000 non-null   int64
 9   Customer_Rating  755 non-null    float64
 10  Payment_Mode     1000 non-null   object
 11  Delivery_Type    1000 non-null   object
 12  Seller_Name      1000 non-null   object
dtypes: float64(3), int64(2), object(8)
memory usage: 101.7+ KB

In [7]:
df["Quantity"].unique()

array(['two', '3', '4', '2', nan, '5', '1'], dtype=object)

In [8]:
df[df["Quantity"] == "two"]

,Order_ID,Date,City,Product_Name,Category,Quantity,Unit_Price,Total_Sales,Delivery_Time,Customer_Rating,Payment_Mode,Delivery_Type,Seller_Name
0,1001,28-04-2024,Delhi,Wheat Flour 1kg,dairy,two,50.0,250.0,43,4.0,cash,Standard,FreshFarm
9,1010,2024/05/19,Bengaluru,Onion 1kg,dairy,two,50.0,250.0,75,NaN,upi,standard,BakeHouse
10,1011,2024/01/20,delhi,Bun 2pcs,dairy,two,NaN,NaN,27,4.9,cash,standard,GroceryHub
14,1015,2024-04-01,Jaipur,Apple 1kg,Vegetables,two,50.0,200.0,29,4.5,Cash,Standard,SnackBox
26,1027,2024/01/13,Mumbai,Cake 500g,dairy,two,80.0,240.0,83,NaN,Cash,standard,FarmFresh
...,...,...,...,...,...,...,...,...,...,...,...,...,...
960,1961,31-01-2024,Mumbai,Eggs 6pcs,Grocery,two,45.0,135.0,84,4.8,Card,Express,BakeHouse
961,1962,2024-03-18,Delhi,Cake 500g,grocery,two,100.0,300.0,51,4.8,upi,standard,GreenCart
971,1972,2024-03-03,Delhi,Tomato 1kg,Vegetables,two,100.0,400.0,86,4.2,cash,Express,GreenCart
983,1984,26-03-2024,Delhi,Orange 1kg,Poultry,two,70.0,210.0,61,NaN,Card,express,GreenCart
998,1999,2024/03/16,Banglore,Namkeen 500g,Bakery,two,85.0,255.0,39,4.2,upi,Express,FreshFarm

In [9]:
df["Quantity"] = df["Quantity"].replace("two", 2)

In [10]:


df["Quantity"] = pd.to_numeric(df["Quantity"], errors="coerce")

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Order_ID         1000 non-null   int64
 1   Date             1000 non-null   object
 2   City             1000 non-null   object
 3   Product_Name     1000 non-null   object
 4   Category         1000 non-null   object
 5   Quantity         841 non-null    float64
 6   Unit_Price       923 non-null    float64
 7   Total_Sales      923 non-null    float64
 8   Delivery_Time    1000 non-null   int64
 9   Customer_Rating  755 non-null    float64
 10  Payment_Mode     1000 non-null   object
 11  Delivery_Type    1000 non-null   object
 12  Seller_Name      1000 non-null   object
dtypes: float64(4), int64(2), object(7)
memory usage: 101.7+ KB

In [12]:
df[["Quantity", "Unit_Price", "Total_Sales"]].head(10)

   Quantity  Unit_Price  Total_Sales
0       2.0        50.0        250.0
1       3.0        60.0        180.0
2       4.0        70.0        280.0
3       2.0        55.0        110.0
4       NaN       100.0        300.0
5       4.0        40.0        160.0
6       2.0        85.0        170.0
7       NaN        55.0        165.0
8       NaN        40.0        200.0
9       2.0        50.0        250.0

In [13]:
df[df["Quantity"] * df["Unit_Price"] != df["Total_Sales"]]

,Order_ID,Date,City,Product_Name,Category,Quantity,Unit_Price,Total_Sales,Delivery_Time,Customer_Rating,Payment_Mode,Delivery_Type,Seller_Name
0,1001,28-04-2024,Delhi,Wheat Flour 1kg,dairy,2.0,50.0,250.0,43,4.0,cash,Standard,FreshFarm
4,1005,2024/05/15,Jaipur,Banana 1dozen,Grocery,NaN,100.0,300.0,36,4.0,UPI,express,FarmFresh
7,1008,2024-03-27,delhi,Milk 1L,Bakery,NaN,55.0,165.0,38,4.2,cash,Express,FreshFarm
8,1009,2024-01-27,Delhi,Namkeen 500g,Fruits,NaN,40.0,200.0,55,4.9,Cash,standard,FarmFresh
9,1010,2024/05/19,Bengaluru,Onion 1kg,dairy,2.0,50.0,250.0,75,NaN,upi,standard,BakeHouse
...,...,...,...,...,...,...,...,...,...,...,...,...,...
968,1969,07-06-2024,Jaipur,Chips 200g,Grocery,NaN,70.0,70.0,35,3.5,Card,Express,SnackBox
971,1972,2024-03-03,Delhi,Tomato 1kg,Vegetables,2.0,100.0,400.0,86,4.2,cash,Express,GreenCart
983,1984,26-03-2024,Delhi,Orange 1kg,Poultry,2.0,70.0,210.0,61,NaN,Card,express,GreenCart
988,1989,28-06-2024,Bengaluru,Bread 400g,Bakery,NaN,80.0,240.0,60,4.5,Cash,Express,BakeHouse
998,1999,2024/03/16,Banglore,Namkeen 500g,Bakery,2.0,85.0,255.0,39,4.2,upi,Express,FreshFarm

In [14]:
invalid_sales = df[
    (df["Quantity"].notna()) &
    (df["Unit_Price"].notna()) &
    (df["Total_Sales"].notna()) &
    (df["Quantity"] * df["Unit_Price"] != df["Total_Sales"])
]

invalid_sales

,Order_ID,Date,City,Product_Name,Category,Quantity,Unit_Price,Total_Sales,Delivery_Time,Customer_Rating,Payment_Mode,Delivery_Type,Seller_Name
0,1001,28-04-2024,Delhi,Wheat Flour 1kg,dairy,2.0,50.0,250.0,43,4.0,cash,Standard,FreshFarm
9,1010,2024/05/19,Bengaluru,Onion 1kg,dairy,2.0,50.0,250.0,75,NaN,upi,standard,BakeHouse
14,1015,2024-04-01,Jaipur,Apple 1kg,Vegetables,2.0,50.0,200.0,29,4.5,Cash,Standard,SnackBox
26,1027,2024/01/13,Mumbai,Cake 500g,dairy,2.0,80.0,240.0,83,NaN,Cash,standard,FarmFresh
28,1029,2024/01/01,Mumbai,Chips 200g,dairy,2.0,80.0,240.0,87,4.0,Cash,Express,GreenCart
...,...,...,...,...,...,...,...,...,...,...,...,...,...
960,1961,31-01-2024,Mumbai,Eggs 6pcs,Grocery,2.0,45.0,135.0,84,4.8,Card,Express,BakeHouse
961,1962,2024-03-18,Delhi,Cake 500g,grocery,2.0,100.0,300.0,51,4.8,upi,standard,GreenCart
971,1972,2024-03-03,Delhi,Tomato 1kg,Vegetables,2.0,100.0,400.0,86,4.2,cash,Express,GreenCart
983,1984,26-03-2024,Delhi,Orange 1kg,Poultry,2.0,70.0,210.0,61,NaN,Card,express,GreenCart
998,1999,2024/03/16,Banglore,Namkeen 500g,Bakery,2.0,85.0,255.0,39,4.2,upi,Express,FreshFarm

In [15]:
len(invalid_sales)

93

In [16]:
invalid_sales[["Quantity", "Unit_Price", "Total_Sales"]].head(10)

    Quantity  Unit_Price  Total_Sales
0        2.0        50.0        250.0
9        2.0        50.0        250.0
14       2.0        50.0        200.0
26       2.0        80.0        240.0
28       2.0        80.0        240.0
31       2.0        55.0        165.0
61       2.0        70.0        210.0
77       2.0       100.0        100.0
84       2.0        45.0         45.0
90       2.0       100.0        300.0

In [17]:
df["Calculated_Quantity"] = df["Total_Sales"] / df["Unit_Price"]

df[["Quantity", "Calculated_Quantity"]].head(20)

    Quantity  Calculated_Quantity
0        2.0                  5.0
1        3.0                  3.0
2        4.0                  4.0
3        2.0                  2.0
4        NaN                  3.0
5        4.0                  4.0
6        2.0                  2.0
7        NaN                  3.0
8        NaN                  5.0
9        2.0                  5.0
10       2.0                  NaN
11       NaN                  4.0
12       3.0                  3.0
13       NaN                  NaN
14       2.0                  4.0
15       4.0                  4.0
16       5.0                  NaN
17       NaN                  5.0
18       2.0                  2.0
19       2.0                  2.0

In [18]:
df_clean = df.copy()

In [19]:
df_clean["Quantity"] = df_clean["Quantity"].fillna(
    df_clean["Total_Sales"] / df_clean["Unit_Price"]
)

In [20]:
mask = (
    df_clean["Quantity"].notna()
    & df_clean["Unit_Price"].notna()
    & df_clean["Total_Sales"].notna()
)

df_clean.loc[mask, "Quantity"] = (
    df_clean.loc[mask, "Total_Sales"] / df_clean.loc[mask, "Unit_Price"]
)

In [21]:
invalid = df_clean[
    (df_clean["Quantity"] * df_clean["Unit_Price"]) != df_clean["Total_Sales"]
]

len(invalid)

77

In [22]:
df_clean.isnull().sum()

Order_ID                 0
Date                     0
City                     0
Product_Name             0
Category                 0
Quantity                11
Unit_Price              77
Total_Sales             77
Delivery_Time            0
Customer_Rating        245
Payment_Mode             0
Delivery_Type            0
Seller_Name              0
Calculated_Quantity     77
dtype: int64

In [23]:
df_clean["Unit_Price"] = df_clean["Unit_Price"].fillna(
    df_clean["Total_Sales"] / df_clean["Quantity"]
)

In [24]:
df_clean["Total_Sales"] = df_clean["Total_Sales"].fillna(
    df_clean["Quantity"] * df_clean["Unit_Price"]
)

In [25]:
df_clean.isnull().sum()

Order_ID                 0
Date                     0
City                     0
Product_Name             0
Category                 0
Quantity                11
Unit_Price              77
Total_Sales             77
Delivery_Time            0
Customer_Rating        245
Payment_Mode             0
Delivery_Type            0
Seller_Name              0
Calculated_Quantity     77
dtype: int64

In [26]:
df_clean[df_clean["Unit_Price"].isnull()]

,Order_ID,Date,City,Product_Name,Category,Quantity,Unit_Price,Total_Sales,Delivery_Time,Customer_Rating,Payment_Mode,Delivery_Type,Seller_Name,Calculated_Quantity
10,1011,2024/01/20,delhi,Bun 2pcs,dairy,2.0,NaN,NaN,27,4.9,cash,standard,GroceryHub,NaN
13,1014,24-02-2024,Jaipur,Chicken 1kg,Poultry,NaN,NaN,NaN,39,NaN,upi,Standard,FarmFresh,NaN
16,1017,2024/03/12,Mumbai,Apple 1kg,Dairy,5.0,NaN,NaN,52,NaN,UPI,standard,GroceryHub,NaN
27,1028,14-04-2024,Mumbai,Sugar 1kg,Dairy,2.0,NaN,NaN,53,4.0,upi,Standard,BakeHouse,NaN
35,1036,2024-06-27,Banglore,Bun 2pcs,Dairy,2.0,NaN,NaN,36,4.8,cash,Standard,FarmFresh,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
903,1904,2024-06-24,Bengaluru,Milk 1L,Bakery,4.0,NaN,NaN,48,4.0,UPI,Express,GreenCart,NaN
907,1908,30-01-2024,delhi,Bread 400g,Bakery,2.0,NaN,NaN,31,4.0,cash,standard,GroceryHub,NaN
920,1921,2024/01/07,Jaipur,Eggs 6pcs,Snacks,4.0,NaN,NaN,89,4.9,Card,standard,FarmFresh,NaN
922,1923,2024-06-25,Mumbai,Curd 500g,Bakery,NaN,NaN,NaN,76,4.7,Card,Standard,SnackBox,NaN
957,1958,2024-01-24,Jaipur,Milk 1L,Grocery,3.0,NaN,NaN,36,4.0,UPI,express,FarmFresh,NaN

In [27]:
df_clean[df_clean["Unit_Price"].isnull()][["Quantity","Unit_Price","Total_Sales"]]

     Quantity  Unit_Price  Total_Sales
10        2.0         NaN          NaN
13        NaN         NaN          NaN
16        5.0         NaN          NaN
27        2.0         NaN          NaN
35        2.0         NaN          NaN
..        ...         ...          ...
903       4.0         NaN          NaN
907       2.0         NaN          NaN
920       4.0         NaN          NaN
922       NaN         NaN          NaN
957       3.0         NaN          NaN

[77 rows x 3 columns]

In [28]:
df_clean[df_clean["Total_Sales"].isnull()][["Quantity","Unit_Price","Total_Sales"]]

     Quantity  Unit_Price  Total_Sales
10        2.0         NaN          NaN
13        NaN         NaN          NaN
16        5.0         NaN          NaN
27        2.0         NaN          NaN
35        2.0         NaN          NaN
..        ...         ...          ...
903       4.0         NaN          NaN
907       2.0         NaN          NaN
920       4.0         NaN          NaN
922       NaN         NaN          NaN
957       3.0         NaN          NaN

[77 rows x 3 columns]

In [29]:
df_clean = df_clean.dropna(subset=["Unit_Price", "Total_Sales"])

In [30]:
df_clean.isnull().sum()

Order_ID                 0
Date                     0
City                     0
Product_Name             0
Category                 0
Quantity                 0
Unit_Price               0
Total_Sales              0
Delivery_Time            0
Customer_Rating        219
Payment_Mode             0
Delivery_Type            0
Seller_Name              0
Calculated_Quantity      0
dtype: int64

In [31]:
df_clean.drop(columns=["Calculated_Quantity"], inplace=True)

In [32]:
df_clean["Date"].head(10)

0    28-04-2024
1    09-06-2024
2    12-01-2024
3    2024-06-18
4    2024/05/15
5    2024/05/03
6    27-05-2024
7    2024-03-27
8    2024-01-27
9    2024/05/19
Name: Date, dtype: object

In [33]:
df_clean["Date"] = pd.to_datetime(
    df_clean["Date"],
    format="mixed",
    dayfirst=True
)

In [34]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 923 entries, 0 to 999
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Order_ID         923 non-null    int64
 1   Date             923 non-null    datetime64[ns]
 2   City             923 non-null    object
 3   Product_Name     923 non-null    object
 4   Category         923 non-null    object
 5   Quantity         923 non-null    float64
 6   Unit_Price       923 non-null    float64
 7   Total_Sales      923 non-null    float64
 8   Delivery_Time    923 non-null    int64
 9   Customer_Rating  704 non-null    float64
 10  Payment_Mode     923 non-null    object
 11  Delivery_Type    923 non-null    object
 12  Seller_Name      923 non-null    object
dtypes: datetime64[ns](1), float64(4), int64(2), object(6)
memory usage: 101.0+ KB

In [35]:
df_clean["Date"].head(10)

0   2024-04-28
1   2024-06-09
2   2024-01-12
3   2024-06-18
4   2024-05-15
5   2024-05-03
6   2024-05-27
7   2024-03-27
8   2024-01-27
9   2024-05-19
Name: Date, dtype: datetime64[ns]

In [36]:
print("City:")
print(df_clean["City"].unique())

print("\nCategory:")
print(df_clean["Category"].unique())

print("\nPayment_Mode:")
print(df_clean["Payment_Mode"].unique())

print("\nDelivery_Type:")
print(df_clean["Delivery_Type"].unique())

City:
['Delhi' 'delhi' 'Pune' 'Bengaluru' 'Jaipur' 'Mumbai' 'Banglore']

Category:
['dairy' 'Grocery' 'Vegetables' 'grocery' 'Snacks' 'Bakery' 'Fruits'
 'Dairy' 'Poultry']

Payment_Mode:
['cash' 'UPI' 'Card' 'upi' 'Cash']

Delivery_Type:
['Standard' 'express' 'standard' 'Express']

In [37]:
df_clean["City"] = df_clean["City"].replace({
    "delhi": "Delhi",
    "Banglore": "Bengaluru"
})

In [38]:
df_clean["City"].unique()

array(['Delhi', 'Pune', 'Bengaluru', 'Jaipur', 'Mumbai'], dtype=object)

In [39]:
df_clean["Category"] = df_clean["Category"].str.title()

In [40]:
df_clean["Category"].unique()

array(['Dairy', 'Grocery', 'Vegetables', 'Snacks', 'Bakery', 'Fruits',
       'Poultry'], dtype=object)

In [41]:
df_clean["Payment_Mode"] = df_clean["Payment_Mode"].str.title()

In [42]:
df_clean["Payment_Mode"].unique()

array(['Cash', 'Upi', 'Card'], dtype=object)

In [43]:
df_clean["Payment_Mode"] = df_clean["Payment_Mode"].replace({
    "Upi": "UPI"
})

In [44]:
df_clean["Delivery_Type"] = df_clean["Delivery_Type"].str.title()

In [45]:
df_clean["Delivery_Type"].unique()

array(['Standard', 'Express'], dtype=object)

In [46]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 923 entries, 0 to 999
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Order_ID         923 non-null    int64
 1   Date             923 non-null    datetime64[ns]
 2   City             923 non-null    object
 3   Product_Name     923 non-null    object
 4   Category         923 non-null    object
 5   Quantity         923 non-null    float64
 6   Unit_Price       923 non-null    float64
 7   Total_Sales      923 non-null    float64
 8   Delivery_Time    923 non-null    int64
 9   Customer_Rating  704 non-null    float64
 10  Payment_Mode     923 non-null    object
 11  Delivery_Type    923 non-null    object
 12  Seller_Name      923 non-null    object
dtypes: datetime64[ns](1), float64(4), int64(2), object(6)
memory usage: 101.0+ KB

In [47]:
df_clean.describe(include="all")

,Order_ID,Date,City,Product_Name,Category,Quantity,Unit_Price,Total_Sales,Delivery_Time,Customer_Rating,Payment_Mode,Delivery_Type,Seller_Name
count,923.000000,923,923,923,923,923.000000,923.000000,923.000000,923.000000,704.000000,923,923,923
unique,NaN,NaN,5,20,7,NaN,NaN,NaN,NaN,NaN,3,2,6
top,NaN,NaN,Delhi,Potato 1kg,Grocery,NaN,NaN,NaN,NaN,NaN,Cash,Standard,GreenCart
freq,NaN,NaN,275,57,210,NaN,NaN,NaN,NaN,NaN,394,476,169
mean,1504.789816,2024-04-02 15:36:04.680390144,NaN,NaN,NaN,3.047671,62.437703,190.368364,57.152763,4.375852,NaN,NaN,NaN
min,1001.000000,2024-01-01 00:00:00,NaN,NaN,NaN,1.000000,30.000000,30.000000,25.000000,3.500000,NaN,NaN,NaN
25%,1256.500000,2024-02-18 00:00:00,NaN,NaN,NaN,2.000000,45.000000,100.000000,41.000000,4.000000,NaN,NaN,NaN
50%,1506.000000,2024-04-05 00:00:00,NaN,NaN,NaN,3.000000,60.000000,165.000000,57.000000,4.500000,NaN,NaN,NaN
75%,1753.500000,2024-05-16 00:00:00,NaN,NaN,NaN,4.000000,80.000000,255.000000,74.000000,4.800000,NaN,NaN,NaN
max,2000.000000,2024-06-29 00:00:00,NaN,NaN,NaN,5.000000,100.000000,500.000000,90.000000,4.900000,NaN,NaN,NaN
std,289.059473,NaN,NaN,NaN,NaN,1.386291,21.150867,113.040098,19.176355,0.452635,NaN,NaN,NaN

In [48]:
df_clean["Customer_Rating"] = df_clean["Customer_Rating"].fillna(
    df_clean["Customer_Rating"].median()
)

In [49]:
df_clean.duplicated().sum()

0

In [50]:
df_clean.dtypes

Order_ID                    int64
Date               datetime64[ns]
City                       object
Product_Name               object
Category                   object
Quantity                  float64
Unit_Price                float64
Total_Sales               float64
Delivery_Time               int64
Customer_Rating           float64
Payment_Mode               object
Delivery_Type              object
Seller_Name                object
dtype: object

In [51]:
df_clean.shape

(923, 13)

In [52]:
df_clean.to_csv("Blinkit_Sales_Cleaned.csv", index=False)

In [53]:
(df_clean["Quantity"] % 1).sum()

0.0

In [54]:
df_clean["Quantity"] = df_clean["Quantity"].astype(int)

In [55]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 923 entries, 0 to 999
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Order_ID         923 non-null    int64
 1   Date             923 non-null    datetime64[ns]
 2   City             923 non-null    object
 3   Product_Name     923 non-null    object
 4   Category         923 non-null    object
 5   Quantity         923 non-null    int32
 6   Unit_Price       923 non-null    float64
 7   Total_Sales      923 non-null    float64
 8   Delivery_Time    923 non-null    int64
 9   Customer_Rating  923 non-null    float64
 10  Payment_Mode     923 non-null    object
 11  Delivery_Type    923 non-null    object
 12  Seller_Name      923 non-null    object
dtypes: datetime64[ns](1), float64(3), int32(1), int64(2), object(6)
memory usage: 97.3+ KB

In [57]:
df_clean.to_csv("Blinkit_Sales_Cleaned.csv", index=False)